# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'countApp_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for countApp_MVVM
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  target 'countApp_MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'countApp_MVVMUITests' do
    # Pods for testing
  end

end
